Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  # Auto generated by Rails Bytes: https://railsbytes.com
  # ---------------------------------------------------------
  # Generated by Dom Scordino
  
  root "pages#home" # Defines the root path route ("/")
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create] # we have the show action and index action. Rails expects these to be in the articles controller

end
